___TERMS_OF_SERVICE___

By creating or modifying this file you agree to Google Tag Manager's Community
Template Gallery Developer Terms of Service available at
https://developers.google.com/tag-manager/gallery-tos (or such other URL as
Google may provide), as modified from time to time.


___INFO___

{
  "type": "TAG",
  "id": "cvt_temp_public_id",
  "version": 1,
  "securityGroups": [],
  "displayName": "LinkedIn | CAPI Tag Template",
  "categories": [
    "ADVERTISING",
    "CONVERSIONS"
  ],
  "brand": {
    "id": "github.com_linkedin-developers",
    "displayName": "linkedin-developers",
    "thumbnail": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAB7FBMVEUAAAAKZswMaMQLZ8ILZ8MLZsMKZ8IKZsIkbdsMZsMKZsMKZsOAgP8LaMMKZsMRZsQKZ8MNaMILZ8MMaMIKZsMKZ8ILZsMLZsILZ8ILZ8MMaMQMZ8UOZ8gMZ8IPacMLZ8ILZ8MLaMYLZ8IaZswKZ8MLaMINZsILZ8MMZsIzZswNZ8UKZ8MKZ8INa8MKZsMRZswLZsMLZsQMZ8QVatULZ8MSbcgLZsMKZsIOacQKZ8MMZ8MLZsQKZsINZ8ULZ8QLZ8MLZsULZsMLZsMPbMkKZsIKZ8MLZ8MNasYLaspVqv8rgNUPacMTaMYNZsQLaMQKaMMKZ8MKZ8MKZ8MMaMQLacJAgP8LasUKZ8MLZ8MKZ8ILZ8MMaMMLZsQKZ8ILZ8MOccYNZ8MLZsMLZ8MKacMKZ8QKZ8MQa8ULZ8IOasUMascKZsP///8MZ8MXdNEMbcIKZ8QLZ8INacQLZ8MNaMMKZsIKZsMMZsQLZsQKZ8MLZ8ILb8gKZsMOasYOZsMMZ8MMaMULZsMKZ8INa8kMa8QPZsUKZsMKZ8MKZ8MLZsILZsMKZ8IKZsILZ8IKZsMKZ8MLZsILZsIMZ8QLZ8IKZsIMZsMNacQLZsQSbcgLZsMLZ8MNZswLZ8McccYLZ8QMZ8ILZ8MLZsIKZsIKZsMLZsPDZ/nSAAAApHRSTlMAGWekv9nz/wduyP4CXeAeyzvpWPnJpdaPb1Y+JW0iwdNHqAr9dlBymwU5rfsm+g+7dVcMug6nrDjHmnD8T3SmRsC+IfeZdzoYAwYRGzxbe8T2smwuBDBm7vipQI7i0BJNtpwzkqsfnzUp3AFqCxVjij3xUfT1QV+VzheYJDeDLNR+Eysj4eSuoOrfxbWvzPDmUrixa05aHOizFEgJoyqItNvl8nYMZNQAAAUGSURBVHgB7NZToiVRDIXhVUzx2Lat+c+s3dfIc5JvCP9Gglcc1/ODkMQKA99zHXwiipOUFEiTOMJ7WV4gNQp5hjeKJVKlVMQr5QopUynjhWqN1KlVX5x/jRSqlZ/ef4VUqhTxR1YipUoZfstJrRy/RAVSqxABiEmxGECdFKsDTkqKpQ5cUs1Fg1RrwCfVfASkWoCQVAtBylkAC8BiASyABbAAFsACWAALYAEsgAWwABag2Wp3ur1et9NuNfUF8PsDvDDo+6oCDMt4pzxUE2A0xofGIx0BJlN8YjpREGA2xxfmM+kBZgt8aTETHmCJbyxlB1jhWyvJAZI1vrVOBAfYgGEjN8AWLFupAXZ7sOx3QgNMwDQRGqAKpqrMAIcjmI4HkQFOYDuJDHAG21lkgAvYLiIDdMHWFRmgB7aeyABXsF0tgD0B+wRtDNoiJC3ADWw3kQEOdzDdDyID0EXuF8AL8ADTQ2iAXQ8svZ3QAPSTXXtokCuIojh+whvbxlirsW3btm3bcTIxvmhs9a3uDm7V+60f/9s6QWAJIl0DUDAYgknfACGcg5EQjQNQKGwK1ftwNAw2hJHeAcIj8FsRLpoHoPBI/EZkuAETmahfT2SiDBlJReOnouWPpLhifjaTiyHBQIpiL8bhK3EXY4nMm8ru/TCV3av/VFZ/VgArgOGsAFYAw1kBrACGswJYAaTTP0D8yYTE40mXkgNSUtPSfTMyszyyc4wJsDs3L78APygoLNpRrH+AktKrnvilgrLyCq0DVO6tgg0Hqmtc/lIAsNh7J/3Ap7YOLHH1J3QM0OALtsamcN0CxDZDSUusVgFar0JVW/tufQKEdsAOcTs1CXCsGvZJKdciQG4n7NblJz9Adxsc0FMsPIBLHhzT3Cs6QE4fHHW0X3CAgR44bjBHbIAT0XCGTLEBhuAcw0IDlMNJUk+KDDDiCWc5XCwwQHg+nKdIYABXONGBk7ICOF+di+EBMGx6gNF4wwNgzPQA4y6GB0CD6QEmTA+AXaYHmDQ9wJTpATBteoAZLQK0zc7NB8AuR6UHODAxmb1wgt46sbjU7gtVe0pEB/BaXqFvrObtgZo1wQHq1ulHi+2pUNEtNsD8Bv3cZjoUREgNUH2DfuVmM/iSZQY4MLmffi3+Fvj6JQbouE2/VXIUbFcEBjiQSzasjILrjsAAZ8imJf7D5AW4SwzVYNorLkBPODFUtoHnnrQAbZvE4gae89IC3CeeGvDUCQuw5xDxuDwAS4uwAJHE1Q6Ww7ICpGwR10OwPJIV4DGx9aeA44msAE+Jbw4ssgIcI75MDQM8IwXPNQxQRAqiNAxwhhRc1jDAC1LwUsMAp0nBloYBXpGCXg0D9JKCN+3dhYkEURiEwX903SV/2EDP3Q9nu14GXWPY8B2vEOB//z9eIcBfpwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMjvAwAAAAAAAAAAAAAAAAAAAAAAAABwyd5/qSEbYKg+G6CvLhugqzYboK1mkbx/0VSdkgHmVTVLBpg9Jp5iz/qhZbvKBVg9dh63qfu3y3o4m33m/v3mJdR9TNx/fFNwPQQKHA/vYu37uPv/Q8F3sw17/20+NX9X66Dv/2r5VfRydlokrF+cZt+2/Jv23A/j9W4fh75rm3eTbwGgEZTnsjA44QAAAABJRU5ErkJggg\u003d\u003d"
  },
  "description": "LinkedIn's official Google Tag Manager tag template for streaming conversion events from server container to LinkedIn's Conversions API endpoint.",
  "containerContexts": [
    "SERVER"
  ]
}


___TEMPLATE_PARAMETERS___

[
  {
    "type": "TEXT",
    "name": "apiAccessToken",
    "displayName": "LinkedIn API Access Token",
    "simpleValueType": true
  },
  {
    "type": "TEXT",
    "name": "conversionRuleUrn",
    "displayName": "Conversion Rule ID",
    "simpleValueType": true
  },
  {
    "type": "TEXT",
    "name": "eventId",
    "displayName": "EventID - The unique id generated by advertisers to indicate each event. *Optional*",
    "simpleValueType": true
  },
  {
    "type": "TEXT",
    "name": "conversionValue",
    "displayName": "Conversion Value - The monetary value for this conversion. It contains “currencyCode” in ISO format (e.g. “USD”) and the “amount” value of the conversion in decimal string. (e.g. “100.05”). Advertisers can set conversion values dynamically here or set a fix value. ie: \u0027{\"currencyCode\": \"USD\", \"amount\": \"50.0\"}\u0027 *Optional*",
    "simpleValueType": true
  },
  {
    "type": "GROUP",
    "name": "userIds Group",
    "displayName": "User Ids Override",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "LABEL",
        "name": "userIdslabel",
        "displayName": "Tag will attempt to parse cookie/event data but you can provide those parameter explicitly, at least one identifier is needed for a successful request.  The tag automatically collects the following fields in this order of precedence: <ul><li><b>Email</b> — (1) manual override, (2) <i>user_data.sha256_email_address</i>, (3) <i>eventModel.email</i>, (4) <i>user_data.email_address</i>, (5) <i>user_data.email</i>, (6) <i>eventModel.user_email_auto</i> (GTM User-Provided Data variable, AUTO mode), (7) <i>user_provided_data_automatic.email</i>. If not already SHA256-hashed, it will be hashed automatically before being sent.</li><li><b>IP Address</b> — (1) manual override, (2) <i>user_data.ip_address</i>, (3) <i>eventModel.ip_override</i> (auto-captured by the GA4 server-side client).</li></ul>"
      },
      {
        "type": "SIMPLE_TABLE",
        "name": "userIds",
        "simpleTableColumns": [
          {
            "defaultValue": "",
            "displayName": "Property Name",
            "name": "name",
            "type": "SELECT",
            "selectItems": [
              {
                "value": "email",
                "displayValue": "SHA256_EMAIL"
              },
              {
                "value": "linkedinFirstPartyId",
                "displayValue": "LINKEDIN_FIRST_PARTY_ADS_TRACKING_UUID"
              },
              {
                "value": "acxiomID",
                "displayValue": "ACXIOM ID"
              },
              {
                "value": "moatID",
                "displayValue": "ORACLE_MOAT_ID"
              },
              {
                "value": "ipAddress",
                "displayValue": "PLAINTEXT_IP_ADDRESS"
              },
              {
                "value": "googleAid",
                "displayValue": "GOOGLE_AID"
              }
            ]
          },
          {
            "defaultValue": "",
            "displayName": "Property Value",
            "name": "value",
            "type": "TEXT"
          }
        ],
        "newRowButtonText": "Add Property"
      }
    ]
  },
  {
    "type": "GROUP",
    "name": "userInfoGroup",
    "displayName": "User Info Override",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "LABEL",
        "name": "userInfoLabel",
        "displayName": "Tag will automatically collect the following user info fields in this order of precedence: <ul><li><b>First Name</b> — (1) manual override, (2) <i>eventModel.firstName</i> / <i>eventModel.FirstName</i> / <i>eventModel.nameFirst</i> / <i>eventModel.first_name</i>, (3) <i>user_data.first_name</i>, (4) <i>user_address.first_name</i>, (5) <i>eventModel.user_first_name_auto</i> (GTM User-Provided Data variable, AUTO mode), (6) <i>user_provided_data_automatic.address.first_name</i>.</li><li><b>Last Name</b> — (1) manual override, (2) <i>eventModel.lastName</i> / <i>eventModel.LastName</i> / <i>eventModel.nameLast</i> / <i>eventModel.last_name</i>, (3) <i>user_data.last_name</i>, (4) <i>user_address.last_name</i>, (5) <i>eventModel.user_last_name_auto</i> (GTM User-Provided Data variable, AUTO mode), (6) <i>user_provided_data_automatic.address.last_name</i>.</li><li><b>Country Code</b> — (1) manual override, (2) <i>eventModel.countryCode</i> / <i>eventModel.country</i>, (3) <i>user_data.country</i>, (4) <i>user_address.country</i>, (5) <i>eventModel.user_country_auto</i> (GTM User-Provided Data variable, AUTO mode), (6) <i>user_provided_data_automatic.address.country</i>.</li></ul>At least First Name and Last Name are required when sending User Info."
      },
      {
        "type": "SIMPLE_TABLE",
        "name": "userInfo",
        "simpleTableColumns": [
          {
            "defaultValue": "",
            "displayName": "Property Name",
            "name": "name",
            "type": "SELECT",
            "selectItems": [
              {
                "value": "firstName",
                "displayValue": "First Name"
              },
              {
                "value": "lastName",
                "displayValue": "Last Name"
              },
              {
                "value": "jobTitle",
                "displayValue": "Job Title"
              },
              {
                "value": "companyName",
                "displayValue": "Company Name"
              },
              {
                "value": "countryCode",
                "displayValue": "Country Code"
              }
            ]
          },
          {
            "defaultValue": "",
            "displayName": "Property Value",
            "name": "value",
            "type": "TEXT"
          }
        ],
        "newRowButtonText": "Add Property"
      }
    ]
  },
  {
    "type": "GROUP",
    "name": "eventDataGroup",
    "displayName": "Event Data Override",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "SIMPLE_TABLE",
        "name": "eventData",
        "simpleTableColumns": [
          {
            "defaultValue": "",
            "displayName": "Property Name",
            "name": "name",
            "type": "SELECT",
            "selectItems": [
              {
                "value": "conversionHappenedAt",
                "displayValue": "Conversion Happened At"
              },
              {
                "value": "currency",
                "displayValue": "Currency"
              },
              {
                "value": "amount",
                "displayValue": "Amount"
              },
              {
                "value": "eventId",
                "displayValue": "Event ID"
              }
            ]
          },
          {
            "defaultValue": "",
            "displayName": "Property Value",
            "name": "value",
            "type": "TEXT"
          }
        ],
        "newRowButtonText": "Add property",
        "valueValidators": []
      }
    ]
  }
]


___SANDBOXED_JS_FOR_SERVER___

// LinkedIn Conversion API documentation: https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/conversions-api

// Sandbox Javascript API imports
// Required GTM Server-Side functions/modules
const sendHttpRequest = require('sendHttpRequest');
const getTimestampMillis = require('getTimestampMillis');
const getAllEventData = require('getAllEventData');
const getEventData = require('getEventData');
const Math = require('Math');
const JSON = require('JSON');
const makeString = require('makeString');
const makeNumber = require('makeNumber');
const logToConsole = require('logToConsole');
const sha256Sync = require('sha256Sync');
const getType = require('getType');
const encodeUriComponent = require('encodeUriComponent');
const makeTableMap = require('makeTableMap');

// Constants
const CONV_API_ENDPOINT = "https://api.linkedin.com/rest/conversionEvents/";
const linkedin_api_version = '202605'; // LinkedIn API version (valid for 1 year from release)

// Input / Event Data Setup
const eventModel = getAllEventData();
const user_data = eventModel.user_data || {};
const user_address_raw = user_data.address || {};
const user_address = getType(user_address_raw) === 'array' ? (user_address_raw[0] || {}) : user_address_raw;
// Automatically-collected user-provided data (GTM User-Provided Data variable, AUTO mode)
const user_provided_data_automatic = eventModel.user_provided_data_automatic || {};
const auto_address_raw = user_provided_data_automatic.address || {};
const auto_address = getType(auto_address_raw) === 'array' ? (auto_address_raw[0] || {}) : auto_address_raw;
const eventDataOverride = makeOverrideTableMap(data.eventData);
const userIdsOverride = makeOverrideTableMap(data.userIds);
const userInfoOverride = makeOverrideTableMap(data.userInfo);

// Conversion Rule URN Construction
const conversion_rule_id = eventModel.conversion_rule_id || data.conversionRuleUrn;
const conversion_rule_urn = 'urn:lla:llaPartnerConversion:' + conversion_rule_id;

// Build conversion event payload
//Check if the conversion Happened time is provided by the user, if not then use the current timestamp.
const conversion_event = {
    conversion_happened_at: makeNumber(eventDataOverride.conversionHappenedAt || eventModel.conversion_happened_at || eventModel.event_time) || Math.round(getTimestampMillis()),
    userData: {
        userIds: getUserIds()
    }
};

// Add LinkedIn LeadGen lead ID if available
if (eventModel.user_data != null && eventModel.user_data.leadID != null) {
    const leadId = eventModel.user_data.leadID;
    const leadIdUrn = leadId !== "" ? 'urn:li:leadGenFormResponse:' + leadId : '';
    conversion_event.userData.lead = leadIdUrn;
}

// Conversion metadata
const eventID = eventDataOverride.eventId || data.eventId || eventModel.eventId || eventModel.event_id || '';
const conversionCurrency = eventDataOverride.currency || eventModel.currency || '';
const conversionAmount = eventDataOverride.amount || eventModel.value || '0';
const conversionValue = data.conversionValue ? JSON.parse(data.conversionValue) : {
    currencyCode: conversionCurrency,
    amount: conversionAmount.toString()
};

// Add user info if available
const userDataInfo = getUserInfo();
if (userDataInfo && userDataInfo.firstName && userDataInfo.lastName) {
    conversion_event.userData.userInfo = userDataInfo;
}

// HTTP request headers
const requestHeaders = {
    'content-type': 'application/json',
    'Authorization': 'Bearer ' + data.apiAccessToken,
    'LinkedIn-Version': linkedin_api_version
};

// Construct request payload
let postBody = {
    conversion: conversion_rule_urn,
    conversionHappenedAt: conversion_event.conversion_happened_at,
    eventId: eventID,
    user: conversion_event.userData
};

if (conversionValue.currencyCode !== "" && conversionValue.amount > 0) {
    postBody.conversionValue = conversionValue;
}

// Main validation + send logic
if (validateUserData()) {
    sendConversionToLinkedIn();
} else {
    logToConsole('No conversion event was sent to CAPI. You must set 1 out of the 4 acceptable IDs (Acxiom, Oracle, SHA256_Email, or LinkedIn_UUID) or provide firstName & lastName under eventModel.user_data.address.');
}

// Validates presence of at least one required ID or name
function validateUserData() {
    let data_is_valid_flag = false;
    const userIDs = conversion_event.userData.userIds;

    for (let user_id of userIDs) {
        if (user_id.idValue !== "") {
            data_is_valid_flag = true;
            break;
        }
    }

    if (!data_is_valid_flag) {
        const userInfo = conversion_event.userData.userInfo;
        if (userInfo && userInfo.firstName && userInfo.lastName) {
            data_is_valid_flag = true;
        }
    }

    return data_is_valid_flag;
}

// Converts array of overrides into map
function makeOverrideTableMap(values) {
    return makeTableMap(values || [], 'name', 'value') || {};
}

// Gathers available user IDs
function getUserIds() {
    const userIds = [{
            idType: 'SHA256_EMAIL',
            idValue: hashData(getUserEmail())
        },
        {
            idType: 'ACXIOM_ID',
            idValue: getAcxiomId()
        },
        {
            idType: 'ORACLE_MOAT_ID',
            idValue: getOracleMoatId()
        },
        {
            idType: 'LINKEDIN_FIRST_PARTY_ADS_TRACKING_UUID',
            idValue: getFirstPartyAdsTrackingUuid()
        },
        {
            idType: 'PLAINTEXT_IP_ADDRESS',
            idValue: getPlaintextIpAddress()
        },
        {
            idType: 'GOOGLE_AID',
            idValue: getGoogleAid()
        }
    ];

    return userIds.filter(userId => userId.idValue);
}

// Gets email, prioritizing hashed version
function getUserEmail() {
    const hashedEmail = getUserDataHashedEmail();

    return (
        (userIdsOverride.email ||
            hashedEmail ||
            eventModel.email ||
            user_data.email_address ||
            user_data.email ||
            eventModel.user_email_auto ||
            user_provided_data_automatic.email ||
            '')
        .toLowerCase()
    );
}

function getUserDataHashedEmail() {
    return user_data && user_data.sha256_email_address ? user_data.sha256_email_address : '';
}

function getAcxiomId() {
    return userIdsOverride.acxiomID || user_data.acxiomID || '';
}

function getOracleMoatId() {
    return userIdsOverride.moatID || user_data.moatID || '';
}

function getPlaintextIpAddress() {
    // eventModel.ip_override is the client IP auto-captured by the GA4 server-side client.
    // No IPv4 validation here so IPv6 values pass through (IPv6 matching not supported yet).
    return userIdsOverride.ipAddress || user_data.ip_address || eventModel.ip_override || '';
}

function getGoogleAid() {
    return userIdsOverride.googleAid || user_data.googleAid || user_data.gaid || '';
}


// Gets LinkedIn first-party UUID
function getFirstPartyAdsTrackingUuid() {
    let eventLinkedinFirstPartyID = '';

    if (
      userIdsOverride &&
      userIdsOverride.linkedinFirstPartyId &&
      userIdsOverride.linkedinFirstPartyId.trim() !== ''
    ) {
      eventLinkedinFirstPartyID = userIdsOverride.linkedinFirstPartyId.trim();
    } else if (
      eventModel &&
      eventModel.user_data &&
      eventModel.user_data.linkedinFirstPartyId &&
      eventModel.user_data.linkedinFirstPartyId.trim() !== ''
    ) {
      eventLinkedinFirstPartyID = eventModel.user_data.linkedinFirstPartyId.trim();
    } else if (
      eventModel &&
      eventModel.li_fat_id &&
      makeString(eventModel.li_fat_id).trim() !== ''
    ){
      // Raw li_fat_id cookie value from the GTM 1st-Party Cookie variable
      eventLinkedinFirstPartyID = makeString(eventModel.li_fat_id).trim();
    }
    const ga4UserPropPrefix = 'x-ga-mp2-user_properties.';
    const userLinkedinFirstPartyID = getEventData(ga4UserPropPrefix + 'linkedinFirstPartyId') || '';
    return eventLinkedinFirstPartyID || userLinkedinFirstPartyID || '';
}

// Fallback lookup for user information
function getUserFirstName() {
    return (
        userInfoOverride.firstName ||
        eventModel.firstName ||
        eventModel.FirstName ||
        eventModel.nameFirst ||
        eventModel.first_name ||
        user_data.first_name ||
        user_address.first_name ||
        eventModel.user_first_name_auto ||
        auto_address.first_name ||
        ''
    );
}

function getUserLastName() {
    return (
        userInfoOverride.lastName ||
        eventModel.lastName ||
        eventModel.LastName ||
        eventModel.nameLast ||
        eventModel.last_name ||
        user_data.last_name ||
        user_address.last_name ||
        eventModel.user_last_name_auto ||
        auto_address.last_name ||
        ''
    );
}

function getUserJobTitle() {
    return (
        userInfoOverride.jobTitle ||
        eventModel.jobTitle ||
        user_data.jobTitle ||
        user_data.job_title ||
        ''
    );
}

function getUserCompanyName() {
    return (
        userInfoOverride.companyName ||
        eventModel.companyName ||
        eventModel.company_name ||
        user_data.companyName ||
        user_data.company_name ||
        ''
    );
}

function getUserCountryCode() {
    return (
        userInfoOverride.countryCode ||
        eventModel.countryCode ||
        eventModel.country ||
        user_data.country ||
        user_address.country ||
        eventModel.user_country_auto ||
        auto_address.country ||
        ''
    );
}

// Builds userInfo object
function getUserInfo() {
    return {
        firstName: getUserFirstName(),
        lastName: getUserLastName(),
        title: getUserJobTitle(),
        companyName: getUserCompanyName(),
        countryCode: getUserCountryCode()
    };
}

// Check if a value is already a valid SHA256 hash
function isHashed(value) {
    if (!value) return false;
    return makeString(value).match('^[A-Fa-f0-9]{64}$') !== null;
}

// Hashes non-object and non-array string values if not already hashed
function hashData(value) {
    if (!value) return value;

    const type = getType(value);
    if (type === 'undefined' || value === 'undefined') return undefined;
    if (type === 'object' || type === 'array') return undefined;
    if (isHashed(value)) return value;

    value = makeString(value).trim().toLowerCase();
    return sha256Sync(value, {
        outputEncoding: 'hex'
    });
}

// Encodes a string for URI safety
function enc(data) {
    return encodeUriComponent(data || '');
}

// Send the API request to LinkedIn
function sendConversionToLinkedIn() {
    sendHttpRequest(CONV_API_ENDPOINT, {
        headers: requestHeaders,
        method: 'POST',
    }, JSON.stringify(postBody)).then(result => {
        if (result.statusCode >= 200 && result.statusCode < 300) {
            data.gtmOnSuccess();
        } else {
            data.gtmOnFailure();
        }
    });
}


___SERVER_PERMISSIONS___

[
  {
    "instance": {
      "key": {
        "publicId": "read_event_data",
        "versionId": "1"
      },
      "param": [
        {
          "key": "eventDataAccess",
          "value": {
            "type": 1,
            "string": "any"
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  },
  {
    "instance": {
      "key": {
        "publicId": "send_http",
        "versionId": "1"
      },
      "param": [
        {
          "key": "allowedUrls",
          "value": {
            "type": 1,
            "string": "any"
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  },
  {
    "instance": {
      "key": {
        "publicId": "logging",
        "versionId": "1"
      },
      "param": [
        {
          "key": "environments",
          "value": {
            "type": 1,
            "string": "debug"
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  }
]


___TESTS___

scenarios: []


___NOTES___

Created on 9/27/2023, 11:40:00 AM


